[package]
name = "notify"
version = "0.1.0"
authors = ["atrn0 <14242642+aratasato@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
