version: "3"
services:
  notify:
    container_name: notify
    image: registry.ataran.me/notify:latest
    environment:
      - BBEXCITE_TRAFFIC_COOKIE
      - SLACK_SIGNING_SECRET
      - SLACK_BOT_TOKEN
      - GYAZO_ACCESS_TOKEN
      - ELECTRICITY_NATURE_COOKIE_DENKI_API
